### PR TITLE
Draft blog post about dictionary tricks.

### PR DESCRIPTION
**Pull request by kf0jvt**
Covers `dict.get()`, `dict.setdefault()`, `defaultdict` and `addict`

### CODE REVIEW

**Comment by krmaxwell** [comment]
I'm into it. Probably could use some sort of conclusion, though.

**Comment by krmaxwell** [comment]
Oh and an image with a stack of turtles.........

**Comment by kf0jvt** [comment]
A conclusion, huh? I wonder what we can conclude from this blog entry. Shit is cool?

**Comment by krmaxwell** [comment]
Maybe just a summary or a brief recap of applications?

**Comment by krmaxwell** [comment]
part of #15

**Comment by kf0jvt** [comment]
Alright, I've added some summary text. Let me know how it reads for you now.

**Comment by krmaxwell** [comment]
Looks good. You cool with tomorrow (Tuesday)?

**Comment by kf0jvt** [comment]
Yep, that would be great.

**Pull request merged**
