### PR TITLE
Move feed up a panel to resolve #34

### LINKED ISSUE #34: Minimize the sidebar
Currently, after the title and subtitle, the sidebar has two panels: one with links to some pages ("Home About Contact Archive"), and one with a couple of links ("github twitter rss").

Since Github and Twitter already show up in the Contact page, we should move "RSS" to that link panel and remove the last panel entirely.

### PR DESCRIPTION
**Pull request by krmaxwell**

### CODE REVIEW

**Comment by krmaxwell** [comment]
Ruby just confused me tremendously. What I changed in this commit shouldn't have _anything_ to do with this at all.

Any thoughts @sroberts or @blackfist ?

**Comment by kf0jvt** [comment]
It looks like one of the dependencies is failing to load for some reason. Where is it getting that list of gems that it tries to use? Is that a dependency list coming from jeckyl?

**Comment by krmaxwell** [comment]
It's just in the `github-pages` meta-package (see https://github.com/krmaxwell/krmaxwell.github.io/blob/master/Gemfile)

**Comment by kf0jvt** [comment]
OK. A good rule of thumb in production is to put versions into your gemfile. Otherwise `bundler` will just grab the latest version and that can lead to breakage. However, I would think that if the gemfile was the problem your tests would no longer pass on the master branch either. Can we get Travis to run it's tests on master and see if the problem shows up there as well? That will rule out the actual content change as the source of the problem.

**Comment by krmaxwell** [comment]
Issue with the `github-pages` gem, it turns out: https://github.com/github/pages-gem/issues/122

**Pull request merged**
