### PR TITLE
Advice on CFPs

### LINKED ISSUE #10: CFP advice
- If your approach is to submit to a CFP, then do the research if accepted, you're doing it completely backwards. Stop that.
- Thoughts on overcommitting
- Talks I'd like to see (not give)

### PR DESCRIPTION
**Pull request by krmaxwell**
Closes #10 when merged.

### CODE REVIEW

**Comment by krmaxwell** [comment]
input from wizards @sroberts and @blackfist welcome

**Comment by krmaxwell** [comment]
Need to add a mention of https://danielmiessler.com/blog/hierarchy-information-security-talks/ (and possibly a response to it after I chew on it a bit more)

**Comment by sroberts** [comment]
I like it overall... though i feel like it's aching for a conclusion paragraph.

**Comment by sroberts** [comment]
Operator Overloading feels especially relevant to me.

**Comment by krmaxwell** [comment]
Thanks, you're right. I totally forgot about doing a conclusion. :eyes:

**Comment by sroberts** [comment]
Perfect.

**Comment by sroberts** [comment]
:+1:

**Pull request merged**
