### PR TITLE
Create contact page to close #9

### LINKED ISSUE #9: Create a 'contact' page
http://xwell.org/contact/ is empty :disappointed:

### PR DESCRIPTION
**Pull request by krmaxwell**
:email:, :octocat: (DUH), and :phone: - not sure what else I should include?

### CODE REVIEW

**Comment by sroberts** [comment]
Twitter?

**Comment by sroberts** [comment]
YOLOThreat?

**Comment by krmaxwell** [comment]
Twitter is on the sidebar, think I should put it here too? YOLOthreat, I should make sure I get that :email: working

**Comment by sroberts** [comment]
You have an invite don't you?

**Pull request merged**
