### PR TITLE
Continuous Integration

### PR DESCRIPTION
**Pull request by krmaxwell**
Configuring travis-ci

### CODE REVIEW

**Comment by krmaxwell** [comment]
LOL! Cleanup tiem.

**Comment by krmaxwell** [comment]
```
- ./_site/404.html
  *  External link http://www.room404.com/page.php?pg=homepage failed: got a time out
```

LOL... silliness from my theme.

**Comment by krmaxwell** [comment]
:tada:

**Comment by sroberts** [comment]
blackhat-loki-oh-yes

**Pull request merged**
